[2025-01-04T11:13:55.359-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-04T11:13:55.379-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CovidE2EPipeDag.stage_sql scheduled__2025-01-01T00:57:00+00:00 [queued]>
[2025-01-04T11:13:55.393-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CovidE2EPipeDag.stage_sql scheduled__2025-01-01T00:57:00+00:00 [queued]>
[2025-01-04T11:13:55.394-0800] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-04T11:13:55.424-0800] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): stage_sql> on 2025-01-01 00:57:00+00:00
[2025-01-04T11:13:55.430-0800] {standard_task_runner.py:72} INFO - Started process 76638 to run task
[2025-01-04T11:13:55.451-0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'CovidE2EPipeDag', 'stage_sql', 'scheduled__2025-01-01T00:57:00+00:00', '--job-id', '851', '--raw', '--subdir', 'DAGS_FOLDER/CovidE2EPipeDag.py', '--cfg-path', '/var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T/tmpe8fspihz']
[2025-01-04T11:13:55.456-0800] {standard_task_runner.py:105} INFO - Job 851: Subtask stage_sql
[2025-01-04T11:13:55.570-0800] {task_command.py:467} INFO - Running <TaskInstance: CovidE2EPipeDag.stage_sql scheduled__2025-01-01T00:57:00+00:00 [running]> on host Matthews-MacBook-Air.local
[2025-01-04T11:13:55.741-0800] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matthew Horn' AIRFLOW_CTX_DAG_ID='CovidE2EPipeDag' AIRFLOW_CTX_TASK_ID='stage_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:57:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:57:00+00:00'
[2025-01-04T11:13:55.743-0800] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-04T11:13:55.822-0800] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T
[2025-01-04T11:13:55.825-0800] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'snow stage copy /Users/matthewmac/airflow/helper_scripts/load_staged_data_2025-01-04.sql']
[2025-01-04T11:13:55.851-0800] {subprocess.py:99} INFO - Output:
[2025-01-04T11:13:57.955-0800] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-04T11:13:57.973-0800] {process_utils.py:132} INFO - Sending 15 to group 76638. PIDs of all processes in the group: [76639, 76638]
[2025-01-04T11:13:57.974-0800] {process_utils.py:87} INFO - Sending the signal 15 to group 76638
[2025-01-04T11:13:57.976-0800] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-04T11:13:57.977-0800] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-01-04T11:13:58.008-0800] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-01-04T11:13:58.024-0800] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=CovidE2EPipeDag, task_id=stage_sql, run_id=scheduled__2025-01-01T00:57:00+00:00, execution_date=20250101T005700, start_date=20250104T191355, end_date=20250104T191358
[2025-01-04T11:13:58.053-0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-04T11:13:58.087-0800] {process_utils.py:80} INFO - Process psutil.Process(pid=76638, status='terminated', exitcode=2, started='11:13:55') (76638) terminated with exit code 2
[2025-01-04T11:13:58.089-0800] {process_utils.py:80} INFO - Process psutil.Process(pid=76639, status='terminated', started='11:13:55') (76639) terminated with exit code None
[2025-01-04T11:14:38.247-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-04T11:14:38.273-0800] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: CovidE2EPipeDag.stage_sql scheduled__2025-01-01T00:57:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-01-04T11:14:38.274-0800] {local_task_job_runner.py:166} INFO - Task is not able to be run
